// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int graetercount = 0;
		int smallercount = 0;
		double check;
		for(int i = 0; i< N; i++){
			check = Math.random();
			if(check >  0.5){ 
				graetercount++;
			} else{
				smallercount++;
			}
		}
		double Ratio;
		if(graetercount < smallercount){
			Ratio = (double) graetercount / smallercount;
		}else{
			Ratio = (double) smallercount / graetercount;
		}
		System.out.println("> 0.5: "+ graetercount + " times");
		System.out.println("<= 0.5: " + smallercount + " times");
		System.out.println("Ratio: " + Ratio);
		
	}
}
